/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "sub.h"

bool_t
xdr_inputs (XDR *xdrs, inputs *objp)
{
	register int32_t *buf;


	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, 6 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->turn))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->x1))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->y1))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->x0))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->y0))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->returnVal))
				 return FALSE;
		} else {
			IXDR_PUT_LONG(buf, objp->turn);
			IXDR_PUT_LONG(buf, objp->x1);
			IXDR_PUT_LONG(buf, objp->y1);
			IXDR_PUT_LONG(buf, objp->x0);
			IXDR_PUT_LONG(buf, objp->y0);
			IXDR_PUT_LONG(buf, objp->returnVal);
		}
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, 6 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->turn))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->x1))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->y1))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->x0))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->y0))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->returnVal))
				 return FALSE;
		} else {
			objp->turn = IXDR_GET_LONG(buf);
			objp->x1 = IXDR_GET_LONG(buf);
			objp->y1 = IXDR_GET_LONG(buf);
			objp->x0 = IXDR_GET_LONG(buf);
			objp->y0 = IXDR_GET_LONG(buf);
			objp->returnVal = IXDR_GET_LONG(buf);
		}
	 return TRUE;
	}

	 if (!xdr_int (xdrs, &objp->turn))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->x1))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->y1))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->x0))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->y0))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->returnVal))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_outputs (XDR *xdrs, outputs *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->x0))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->y0))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->returnVal))
		 return FALSE;
	return TRUE;
}
