/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "sub.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

outputs *
server_move_1(inputs *argp, CLIENT *clnt)
{
	static outputs clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, SERVER_MOVE,
		(xdrproc_t) xdr_inputs, (caddr_t) argp,
		(xdrproc_t) xdr_outputs, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
