/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SUB_H_RPCGEN
#define _SUB_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct inputs {
	int turn;
	int x1;
	int y1;
	int x0;
	int y0;
	int returnVal;
};
typedef struct inputs inputs;


struct outputs {
	int x0;
	int y0;
	int returnVal;
};
typedef struct outputs outputs;


#define SUBPROG 0x31728436
#define SUBVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define SERVER_MOVE 1
extern  outputs * server_move_1(inputs *, CLIENT *);
extern  outputs * server_move_1_svc(inputs *, struct svc_req *);
extern int subprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SERVER_MOVE 1
extern  outputs * server_move_1();
extern  outputs * server_move_1_svc();
extern int subprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_inputs (XDR *, inputs*);
extern  bool_t xdr_inputs (XDR *, inputs*);
extern  bool_t xdr_outputs (XDR *, outputs*);
extern  bool_t xdr_outputs (XDR *, outputs*);

#else /* K&R C */
extern bool_t xdr_inputs ();
extern bool_t xdr_inputs ();
extern bool_t xdr_outputs ();
extern bool_t xdr_outputs ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SUB_H_RPCGEN */
