BEGIN {
S["am__EXEEXT_FALSE"]=""
S["am__EXEEXT_TRUE"]="#"
S["LTLIBOBJS"]=""
S["M2S_INCLUDES"]=" -I$(top_srcdir) -I$(top_srcdir)/src "
S["PKGDATADIR"]="${datarootdir}/multi2sim"
S["DATADIR"]="${prefix}/share"
S["HAVE_GTK_FALSE"]=""
S["HAVE_GTK_TRUE"]="#"
S["GTK_LIBS"]=""
S["GTK_CFLAGS"]=""
S["PKG_CONFIG"]="/usr/bin/pkg-config"
S["LLVM_LIBS"]=""
S["LLVM_LDFLAGS"]=""
S["LLVM_CXXFLAGS"]=""
S["LLVM_CFLAGS"]=""
S["HAVE_FLEX_BISON_AND_LLVM_FALSE"]=""
S["HAVE_FLEX_BISON_AND_LLVM_TRUE"]="#"
S["HAVE_LLVM_FALSE"]=""
S["HAVE_LLVM_TRUE"]="#"
S["HAVE_CXX_FALSE"]="#"
S["HAVE_CXX_TRUE"]=""
S["HAVE_FLEX_BISON_FALSE"]="#"
S["HAVE_FLEX_BISON_TRUE"]=""
S["YFLAGS"]=""
S["YACC"]="bison -y"
S["LEXLIB"]="-lfl"
S["LEX_OUTPUT_ROOT"]="lex.yy"
S["LEX"]="flex"
S["HAVE_OPENGL_FALSE"]=""
S["HAVE_OPENGL_TRUE"]="#"
S["OPENGL_LDFLAGS"]="-lGL -lGLU -lGLEW -lglut"
S["HAVE_OPENCL_FALSE"]=""
S["HAVE_OPENCL_TRUE"]="#"
S["HAVE_M32_FLAG_FALSE"]="#"
S["HAVE_M32_FLAG_TRUE"]=""
S["HAVE_SYNC_BUILTINS_FALSE"]="#"
S["HAVE_SYNC_BUILTINS_TRUE"]=""
S["LIBOBJS"]=""
S["CXXCPP"]="g++ -E"
S["CPP"]="gcc -E"
S["OTOOL64"]=""
S["OTOOL"]=""
S["LIPO"]=""
S["NMEDIT"]=""
S["DSYMUTIL"]=""
S["MANIFEST_TOOL"]=":"
S["RANLIB"]="ranlib"
S["ac_ct_AR"]="ar"
S["AR"]="ar"
S["DLLTOOL"]="false"
S["OBJDUMP"]="objdump"
S["LN_S"]="ln -s"
S["NM"]="/usr/bin/nm -B"
S["ac_ct_DUMPBIN"]=""
S["DUMPBIN"]=""
S["LD"]="/usr/bin/ld -m elf_x86_64"
S["FGREP"]="/bin/grep -F"
S["EGREP"]="/bin/grep -E"
S["GREP"]="/bin/grep"
S["SED"]="/bin/sed"
S["host_os"]="linux-gnu"
S["host_vendor"]="unknown"
S["host_cpu"]="x86_64"
S["host"]="x86_64-unknown-linux-gnu"
S["build_os"]="linux-gnu"
S["build_vendor"]="unknown"
S["build_cpu"]="x86_64"
S["build"]="x86_64-unknown-linux-gnu"
S["LIBTOOL"]="$(SHELL) $(top_builddir)/libtool"
S["AM_BACKSLASH"]="\\"
S["AM_DEFAULT_VERBOSITY"]="0"
S["AM_DEFAULT_V"]="$(AM_DEFAULT_VERBOSITY)"
S["AM_V"]="$(V)"
S["am__fastdepCXX_FALSE"]="#"
S["am__fastdepCXX_TRUE"]=""
S["CXXDEPMODE"]="depmode=gcc3"
S["ac_ct_CXX"]="g++"
S["CXXFLAGS"]="-g -O2"
S["CXX"]="g++"
S["am__fastdepCCAS_FALSE"]="#"
S["am__fastdepCCAS_TRUE"]=""
S["CCASDEPMODE"]="depmode=gcc3"
S["CCASFLAGS"]="-g -O2"
S["CCAS"]="gcc"
S["am__fastdepCC_FALSE"]="#"
S["am__fastdepCC_TRUE"]=""
S["CCDEPMODE"]="depmode=gcc3"
S["am__nodep"]="_no"
S["AMDEPBACKSLASH"]="\\"
S["AMDEP_FALSE"]="#"
S["AMDEP_TRUE"]=""
S["am__quote"]=""
S["am__include"]="include"
S["DEPDIR"]=".deps"
S["OBJEXT"]="o"
S["EXEEXT"]=""
S["ac_ct_CC"]="gcc"
S["CPPFLAGS"]=""
S["LDFLAGS"]=""
S["CFLAGS"]="-msse2 -O3 -std=gnu99 -DNDEBUG"
S["CC"]="gcc"
S["am__untar"]="$${TAR-tar} xf -"
S["am__tar"]="$${TAR-tar} chof - \"$$tardir\""
S["AMTAR"]="$${TAR-tar}"
S["am__leading_dot"]="."
S["SET_MAKE"]=""
S["AWK"]="gawk"
S["mkdir_p"]="/bin/mkdir -p"
S["MKDIR_P"]="/bin/mkdir -p"
S["INSTALL_STRIP_PROGRAM"]="$(install_sh) -c -s"
S["STRIP"]="strip"
S["install_sh"]="${SHELL} /afs/nd.edu/coursefa.14/cse/cse30321.01/multi2sim/multi2sim-4.2/install-sh"
S["MAKEINFO"]="${SHELL} /afs/nd.edu/coursefa.14/cse/cse30321.01/multi2sim/multi2sim-4.2/missing --run makeinfo"
S["AUTOHEADER"]="${SHELL} /afs/nd.edu/coursefa.14/cse/cse30321.01/multi2sim/multi2sim-4.2/missing --run autoheader"
S["AUTOMAKE"]="${SHELL} /afs/nd.edu/coursefa.14/cse/cse30321.01/multi2sim/multi2sim-4.2/missing --run automake-1.11"
S["AUTOCONF"]="${SHELL} /afs/nd.edu/coursefa.14/cse/cse30321.01/multi2sim/multi2sim-4.2/missing --run autoconf"
S["ACLOCAL"]="${SHELL} /afs/nd.edu/coursefa.14/cse/cse30321.01/multi2sim/multi2sim-4.2/missing --run aclocal-1.11"
S["VERSION"]="4.2"
S["PACKAGE"]="multi2sim"
S["CYGPATH_W"]="echo"
S["am__isrc"]=""
S["INSTALL_DATA"]="${INSTALL} -m 644"
S["INSTALL_SCRIPT"]="${INSTALL}"
S["INSTALL_PROGRAM"]="${INSTALL}"
S["target_alias"]=""
S["host_alias"]=""
S["build_alias"]=""
S["LIBS"]=""
S["ECHO_T"]=""
S["ECHO_N"]="-n"
S["ECHO_C"]=""
S["DEFS"]="-DPACKAGE_NAME=\\\"multi2sim\\\" -DPACKAGE_TARNAME=\\\"multi2sim\\\" -DPACKAGE_VERSION=\\\"4.2\\\" -DPACKAGE_STRING=\\\"multi2sim\\ 4.2\\\" -DPACKAGE_BUGREPORT=\\\"\\\" "\
"-DPACKAGE_URL=\\\"\\\" -DPACKAGE=\\\"multi2sim\\\" -DVERSION=\\\"4.2\\\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRI"\
"NG_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\\\".libs/\\\" -DSTDC_H"\
"EADERS=1 -DHAVE_SYS_WAIT_H=1 -DHAVE_FCNTL_H=1 -DHAVE_FLOAT_H=1 -DHAVE_STDDEF_H=1 -DHAVE_STDINT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_SYS_IO"\
"CTL_H=1 -DHAVE_SYS_SOCKET_H=1 -DHAVE_SYS_TIME_H=1 -DHAVE_UNISTD_H=1 -DHAVE_UTIME_H=1 -DHAVE_ELF_H=1 -DHAVE_STRUCT_STAT_ST_BLKSIZE=1 -DHAVE_STRUCT_ST"\
"AT_ST_BLOCKS=1 -DHAVE_ST_BLOCKS=1 -DHAVE_STRUCT_STAT_ST_RDEV=1 -DHAVE_UNISTD_H=1 -DHAVE_CHOWN=1 -DLSTAT_FOLLOWS_SLASHED_SYMLINK=1 -DHAVE_STDLIB_H=1 "\
"-DHAVE_MALLOC=1 -DHAVE_STDLIB_H=1 -DHAVE_UNISTD_H=1 -DHAVE_SYS_PARAM_H=1 -DHAVE_GETPAGESIZE=1 -DHAVE_MMAP=1 -DHAVE_STDLIB_H=1 -DHAVE_REALLOC=1 -DHAV"\
"E_ALARM=1 -DHAVE_BZERO=1 -DHAVE_FTRUNCATE=1 -DHAVE_GETCWD=1 -DHAVE_GETTIMEOFDAY=1 -DHAVE_MEMSET=1 -DHAVE_MKDIR=1 -DHAVE_MUNMAP=1 -DHAVE_SELECT=1 -DH"\
"AVE_SOCKET=1 -DHAVE_STRCASECMP=1 -DHAVE_STRCHR=1 -DHAVE_STRDUP=1 -DHAVE_STRNCASECMP=1 -DHAVE_STRTOL=1 -DHAVE_UTIME=1 -DHAVE_SSE4=1 -DHAVE_SYNC_BUILT"\
"INS=1 -DYYTEXT_POINTER=1 -DHAVE_FLEX_BISON=1"
S["mandir"]="${datarootdir}/man"
S["localedir"]="${datarootdir}/locale"
S["libdir"]="${exec_prefix}/lib"
S["psdir"]="${docdir}"
S["pdfdir"]="${docdir}"
S["dvidir"]="${docdir}"
S["htmldir"]="${docdir}"
S["infodir"]="${datarootdir}/info"
S["docdir"]="${datarootdir}/doc/${PACKAGE_TARNAME}"
S["oldincludedir"]="/usr/include"
S["includedir"]="${prefix}/include"
S["localstatedir"]="${prefix}/var"
S["sharedstatedir"]="${prefix}/com"
S["sysconfdir"]="${prefix}/etc"
S["datadir"]="${datarootdir}"
S["datarootdir"]="${prefix}/share"
S["libexecdir"]="${exec_prefix}/libexec"
S["sbindir"]="${exec_prefix}/sbin"
S["bindir"]="${exec_prefix}/bin"
S["program_transform_name"]="s,x,x,"
S["prefix"]="/usr/local"
S["exec_prefix"]="${prefix}"
S["PACKAGE_URL"]=""
S["PACKAGE_BUGREPORT"]=""
S["PACKAGE_STRING"]="multi2sim 4.2"
S["PACKAGE_VERSION"]="4.2"
S["PACKAGE_TARNAME"]="multi2sim"
S["PACKAGE_NAME"]="multi2sim"
S["PATH_SEPARATOR"]=":"
S["SHELL"]="/bin/sh"
  for (key in S) S_is_set[key] = 1
  FS = ""

}
{
  line = $ 0
  nfields = split(line, field, "@")
  substed = 0
  len = length(field[1])
  for (i = 2; i < nfields; i++) {
    key = field[i]
    keylen = length(key)
    if (S_is_set[key]) {
      value = S[key]
      line = substr(line, 1, len) "" value "" substr(line, len + keylen + 3)
      len += length(value) + length(field[++i])
      substed = 1
    } else
      len += 1 + keylen
  }

  print line
}

